# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Stephen M. Lee 
email: smlee.981@gmail.com
description: Personal Website

# Cadre settings
# navbar_img: assets/images/logo.png
# favicon_img: assets/images/favicon.png
about: A blog with "notes to self" for all things technincal.  
pagination: 3
favicon_img: assets/images/steve-logo.png
google_analytics: UA-138925131-1

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://stephenlee.info" # the base hostname & protocol for your site, e.g. http://example.com

theme: jekyll-theme-cadre

# Markdown option 
markdown: kramdown
kramdown:
  math_engine_opts:
    preview:         true
    preview_as_code: true

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
